### ISSUE TITLE
Migrate to this broker from cdn-broker and domain-broker

### ISSUE THREAD

**Issue by tammersaleh** [cloud-gov/external-domain-broker#26]

**Comment by bengerman13** [comment]
CF migrate service is going to be a key piece of migrating cdn-service and custom-domain-service instances to external-domain service, but it doesn't talk to either broker.

I think the migration will look something like a periodic task that checks instances in the cdn-broker and custom-domain-broker. It should scan all the active instances, and check the DNS to see if the owner has created the required CNAME/ALIAS records. When it finds a service that has, it should:
- make sure the service instance is not due to renew its certificate soon (maybe next 24 hours?)
- call cf migrate-service
- create a service_instance record in the external-domain-broker database.
  - for cdn service, the record should know the distribution id, the header, cookie, and origin settings. Because of the old broker's architecture, this will mean getting the distribution config from cloudfront and parsing it.
  - for alb service, the record should know the alb arn
- create a certificate record in the external-domain-broker database
- link the certificate as the current and new certificate for the existing instance
- create an update operation record in the external domain broker database. It would probably work to just have this be the normal update operation, but it might be worthwhile to create a new operation type and pipeline just for this kind of update.
- delete or mark canceled the old service instance
