### ISSUE TITLE
Add support for CloudFront compression to CDN plan

### ISSUE THREAD

**Issue by akf** [cloud-gov/external-domain-broker#268]
CloudFront can be configured to compress files. Having CloudFront do this rather than doing it at the origin reduces load on the origin. Currently, an external-domain-broker with CDN does not compress files and also does not request compressed files from the origin, so web clients receive uncompressed content from the CDN -- a significant step backward for page performance! 

## Notes

- https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html
- [Slack discussion](https://gsa-tts.slack.com/archives/C09CR1Q9Z/p1677098835217519)

## Acceptance Criteria

- [ ] Determine next steps and acceptance criteria

**Comment by ArsHaider** [comment]
After discussion with the team it was determined that the best practice in this case was to manually enable CloudFront compression on the CDN for beta.usa.gov. The customer noted after this was manually enabled for beta.usa.gov their performance greatly improved and going forward they may ask that CloudFront compression is also manually turned on for USA.gov's CDN. It was noted that they will continue to communicate with support going forward regarding the details related to this future matter.

Because this required dedicated work on the part of a support engineer for a specific customer, one support hour will be charged regarding this matter. I have already conferred with the business team who noted you all have support hours already available and have enough available towards being charged the 1 hour.
